# Generated by Django 4.2.17 on 2025-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='feedback',
        ),
        migrations.AddField(
            model_name='reservation',
            name='preference',
            field=models.TextField(blank=True),
        ),
    ]
