# Generated by Django 4.2.17 on 2025-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
