# Generated by Django 4.2.17 on 2025-05-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='meal_name',
            new_name='menu_title',
        ),
    ]
