# Generated by Django 4.2.17 on 2025-05-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='meal_title',
            new_name='menu_title',
        ),
    ]
