# Generated by Django 4.2.17 on 2025-02-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_product_orders_meal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal',
            new_name='Menu',
        ),
    ]
