# Generated by Django 4.2.17 on 2025-05-27 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_rename_meal_name_menu_menu_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerFeedback',
            new_name='CustomerComment',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='images',
            new_name='featured_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
