# Generated by Django 4.2.17 on 2025-02-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_orders_customer_remove_orders_meal_menu_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
