# Generated by Django 4.2.17 on 2025-06-02 21:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_options_customercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
