# Generated by Django 4.2.17 on 2025-06-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
