# Generated by Django 4.2.17 on 2025-02-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_category_orders_alter_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
