# Generated by Django 4.2.17 on 2025-02-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menu_category_alter_menu_description_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
