# Generated by Django 4.2.17 on 2025-02-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=200, null=True),
        ),
    ]
