# Generated by Django 4.2.17 on 2025-02-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
