# Generated by Django 4.2.17 on 2025-02-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
