# Generated by Django 4.2.17 on 2025-06-04 12:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_service', models.CharField(choices=[('Table for 2', 'Table for 2'), ('Table for 4', 'Table for 4'), ('Table for 6', 'Table for 6'), ('Table for 10', 'Table for 10'), ('Table for 12', 'Table for 12')], default='Table for 2', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('17:OO PM', '17:00 PM'), ('17:3O PM', '17:30 PM'), ('18:OO PM', '18:00 PM'), ('18:3O PM', '18:30 PM'), ('19:OO PM', '19:OO PM'), ('19:3O PM', '19:3O PM'), ('20:OO PM', '20:00 PM'), ('20:3O PM', '20:30 PM'), ('21:OO PM', '21:00 PM'), ('21:3O PM', '21:30 PM'), ('22:OO PM', '22:OO PM')], default='17:00 PM', max_length=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
