# Generated by Django 4.2.17 on 2025-06-05 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
